### ISSUE TITLE
Can't run egeria-palisade tutorial

### ISSUE THREAD

**Issue by ritwikc** [odpi/egeria-palisade#23]
Hi, I am trying to run egeria-palisade tutorial. I am able to run the jupyter lab. However, I do not see any of the notebooks in egeria side (such as The Administrative Lab, The Asset Management Lab, etc). Hence I am not being able to run the entire tutorial fully. 

Primarily I am not being able to run restricting-asset-access.ipynb. This notebook throws me the first error on the line below and subsequently on all the query commands.  

%%bash
./query.sh "callie quartile" "file:///secured/hr.*" "PROFILE_ACCESS"

Any suggestions or help will be appreciated.

**Comment by planetf1** [comment]
Hi,
 I've been responding in your slack thread at https://odpi.slack.com/archives/CBPRDQPRC/p1584710395043900

Will summarise here later.

**Comment by planetf1** [comment]
I've spent 1/2 day plus taking a look at this.

In summary there's work needed to get the demo working. Some of the challenges include

* The integration is based on/assumes specific levels of projects, and is not maintained with the main releases/master - this also means one needs to use a new clone, rather than easily creating a working environment
* There are some platform specific aspects - for example *nix based scripts, and assumptions about case significance, which cause minor breakages cross platform
* A local k8s and container registry is assumed, rather than being flexible
* The notebook based container setup fails, being unable to retrieve some dependencies - probably as these are constantly changing
* The shell scripts can be fragile if anything changes

None of these are unsurmountable, but require more time to work through between the egeria and palisade teams - in particular the latter.

Perhaps it's a good point to ask what your intent is -- are you trying to learn more about egeria, and metadata management? Or more about palisade specifically? Or very much how the two work together?

Would you want to contribute and feel able to help get these assets working again?

Broadly we need to try and figure out how to best work through this & let you achieve you're ultimate goal. What's the driving need here? There is interesting tech here but the integration needs work and we need to figure when/how much time to put into it . We also want to listen to our community & try and make what we have the most useful possible :-)

**Comment by planetf1** [comment]
No plans to work on this further currently. Will re-open if required
